"""initial schema

Revision ID: 4954be54d1ac
Revises: 
Create Date: 2026-05-16 01:49:54.256642

"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bacs_devices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('node_id', sa.SmallInteger(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('udp_port', sa.Integer(), nullable=False),
    sa.Column('tcp_port', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', 'udp_port', name='uq_bacs_ip_port')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('device_health',
    sa.Column('bacs_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'fail', 'unknown', name='healthstatus'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('consecutive_fail', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bacs_id'], ['bacs_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bacs_id')
    )
    op.create_table('test_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'cancelled', 'failed', name='sessionstatus'), nullable=False),
    sa.Column('device_ids', sa.JSON(), nullable=False),
    sa.Column('total_pairs', sa.Integer(), nullable=False),
    sa.Column('done_pairs', sa.Integer(), nullable=False),
    sa.Column('ok_pairs', sa.Integer(), nullable=False),
    sa.Column('fail_pairs', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_locks',
    sa.Column('bacs_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bacs_id'], ['bacs_devices.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('bacs_id')
    )
    op.create_table('pair_latest_result',
    sa.Column('src_bacs_id', sa.BigInteger(), nullable=False),
    sa.Column('dst_bacs_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('ok', 'fail', name='pairlateststatus'), nullable=False),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dst_bacs_id'], ['bacs_devices.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['src_bacs_id'], ['bacs_devices.id'], ),
    sa.PrimaryKeyConstraint('src_bacs_id', 'dst_bacs_id')
    )
    op.create_table('test_session_pairs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('src_bacs_id', sa.BigInteger(), nullable=False),
    sa.Column('dst_bacs_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'ok', 'fail', 'skipped', name='pairstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['dst_bacs_id'], ['bacs_devices.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['src_bacs_id'], ['bacs_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pair_dst', 'test_session_pairs', ['dst_bacs_id'], unique=False)
    op.create_index('ix_pair_src', 'test_session_pairs', ['src_bacs_id'], unique=False)
    op.create_index('ix_session_status', 'test_session_pairs', ['session_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_status', table_name='test_session_pairs')
    op.drop_index('ix_pair_src', table_name='test_session_pairs')
    op.drop_index('ix_pair_dst', table_name='test_session_pairs')
    op.drop_table('test_session_pairs')
    op.drop_table('pair_latest_result')
    op.drop_table('device_locks')
    op.drop_table('test_sessions')
    op.drop_table('device_health')
    op.drop_table('users')
    op.drop_table('bacs_devices')
    # ### end Alembic commands ###
